---
# Order Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: tradeflow-production
data:
  POSTGRES_URL: "jdbc:postgresql://order-postgres.tradeflow-infrastructure.svc.cluster.local:5432/order_db"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.tradeflow-infrastructure.svc.cluster.local:29092"
  AUTH_SERVICE_JWKS_URI: "http://auth-service.tradeflow-production.svc.cluster.local:8080/.well-known/jwks.json"
  JWK_SET_URI: "http://auth-service.tradeflow-production.svc.cluster.local:8080/.well-known/jwks.json"
  INVENTORY_SERVICE_URL: "http://inventory-service.tradeflow-production.svc.cluster.local:8083"
  IDENTITY_SERVICE_URL: "http://identity-service.tradeflow-production.svc.cluster.local:8081"
  CATALOG_SERVICE_URL: "http://catalog-service.tradeflow-production.svc.cluster.local:8082"
  ZIPKIN_URL: "http://zipkin.tradeflow-infrastructure.svc.cluster.local:9411"
  SPRING_PROFILES_ACTIVE: "prod"
---
# Order Service Secret
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: tradeflow-production
type: Opaque
stringData:
  POSTGRES_USER: "order"
  POSTGRES_PASSWORD: "order_secret"
---
# Order Service
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: tradeflow-production
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: order-service
---
# Order Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: tradeflow-production
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: order-service
          image: joshua76i/tradeflow-order-service:1.0.0
          ports:
            - containerPort: 8084
              name: http
          envFrom:
            - configMapRef:
                name: order-service-config
            - secretRef:
                name: order-service-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
